/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.MyApp;

import SystemNpruPool.User;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Boss
 */
public class user_genneral extends javax.swing.JFrame {


    /**
     * Creates new form user_genneral
     */
    public user_genneral() {
        initComponents();
    }
  public void close(){
        WindowEvent winclose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        in_uid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        in_Firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        in_Lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        in_Address = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        in_CardId = new javax.swing.JFormattedTextField();
        in_Tel = new javax.swing.JFormattedTextField();
        in_Birthday = new javax.swing.JTextField();
        txt_erroruid = new javax.swing.JLabel();
        txt_errorbirthday = new javax.swing.JLabel();
        txt_errortel = new javax.swing.JLabel();
        txt_errorcardid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-user-group-new-icon.png"))); // NOI18N
        jLabel1.setText("ประเภทผู้ใช้งาน : บุคคลทั่วไป");

        in_uid.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        in_uid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                in_uidFocusLost(evt);
            }
        });
        in_uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_uidActionPerformed(evt);
            }
        });
        in_uid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                in_uidKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel2.setText("รหัสสมาชิก");

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel3.setText("รหัสบัตรประชาชน");

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel4.setText("ชื่อ");

        in_Firstname.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel5.setText("นามสกุล");

        in_Lastname.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel6.setText("วัน/เดือน/ปี เกิด");

        jLabel7.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel7.setText("ที่อยู่ที่สามารถติดต่อได้");

        jLabel8.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jLabel8.setText("เบอร์โทรศัพท์");

        in_Address.setColumns(20);
        in_Address.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        in_Address.setRows(5);
        jScrollPane1.setViewportView(in_Address);

        jButton1.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/File-complete-icon.png"))); // NOI18N
        jButton1.setText("เสร็จสิ้น");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon.png"))); // NOI18N
        jButton2.setText("กลับหน้าหลัก");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        try {
            in_CardId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        in_CardId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                in_CardIdFocusLost(evt);
            }
        });
        in_CardId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_CardIdActionPerformed(evt);
            }
        });

        try {
            in_Tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        in_Tel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                in_TelFocusLost(evt);
            }
        });
        in_Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_TelActionPerformed(evt);
            }
        });

        in_Birthday.setToolTipText("Example 2000-02-28");
        in_Birthday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                in_BirthdayFocusLost(evt);
            }
        });
        in_Birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_BirthdayActionPerformed(evt);
            }
        });

        txt_erroruid.setForeground(new java.awt.Color(255, 0, 0));
        txt_erroruid.setText("..");

        txt_errorbirthday.setForeground(new java.awt.Color(255, 0, 0));
        txt_errorbirthday.setText("..");

        txt_errortel.setForeground(new java.awt.Color(255, 0, 0));
        txt_errortel.setText("..");

        txt_errorcardid.setForeground(new java.awt.Color(255, 0, 0));
        txt_errorcardid.setText("..");

        jLabel9.setText("ประเภทสมาชิก");

        jComboBox1.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "บุคคลภายนอก", "นิสิต - นักศึกษา", "บุคลากร - อาจารย์" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(in_uid, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_erroruid))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(in_Birthday, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(in_Tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_errorbirthday)
                                            .addComponent(txt_errortel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(in_CardId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(in_Firstname, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(in_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_errorcardid))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(in_uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_erroruid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(in_CardId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_errorcardid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(in_Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(in_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_errorbirthday)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(in_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_errortel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        User us = new User();
        int check = 0 ;
        String cUid ="" ;
        String cUcardid="" ; 
        String cUfirstname="";
        String cUlastname="" ;
        String cUbirthday="";
        String cUtel="";
        String cUaddress="";
      //  java.util.Date d = in_Birthday.getDate();

            String in_birth = String.valueOf(in_Birthday.getText());
       //     System.out.println("Date : "+d);
            
        if(in_uid.getText().equals("")
                ||in_CardId.getText().equals("")
                ||in_Firstname.getText().equals("") 
                ||in_Lastname.getText().equals("")
                ||in_birth.equals("")
                ||in_Tel.getText().equals("")
                ||in_Address.getText().equals("")){
        if(in_uid.getText().equals("")){
            cUid="รหัสสมาชิก";
        }
        if(in_CardId.getText().equals("             ")){
            cUcardid ="รหัสบัตรประชาชน";
        }
        if(in_Firstname.getText().equals("")){
            cUfirstname="ชื่อ";
        }
        if(in_Lastname.getText().equals("")){
            cUlastname = "นามสกุล";
        }
        if(in_birth.equals(" ")){
            cUbirthday = "วันเกิด";
        }
        if(in_Tel.getText().equals("          "))
        {
            cUtel = "เบอร์โทรศัพท์";
        }
        if(in_Address.getText().equals("")){
            cUaddress = "ที่อยู่";
        }
        String allnull ="\n"+cUid+"\n"
                +cUcardid+"\n"
                +cUfirstname+"\n"
                +cUlastname+"\n"
                +cUbirthday+"\n"
                +cUtel+"\n"
                +cUaddress;
          JOptionPane.showMessageDialog(null,
	    "กรุณากรอก"+ allnull,
	    "กรุณากรอกข้อมูลให้ครบถ้วน",
	    JOptionPane.WARNING_MESSAGE);
          check = 0 ;
    }
     
     else{
           check = 1;
             menu m = new menu();
                    m.setVisible(true);
        us.InsertUser(Integer.valueOf(in_uid.getText()),in_Firstname.getText(),in_Lastname.getText(),in_Address.getText(),String.valueOf(in_Birthday.getText()),in_CardId.getText(),1,in_Tel.getText());
         JOptionPane.showMessageDialog(null,
	    "บันทึกข้อมูลสำเร็จ.",
	    "",
	    JOptionPane.WARNING_MESSAGE);
       
     }
         
        
           
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        user form5 = new user();
        form5.setVisible(true);
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void in_TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_TelActionPerformed

    private void in_uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_uidActionPerformed

    private void in_uidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_uidFocusLost
        // TODO add your handling code here:
     //   User uch= new User();
      //  boolean checkuid =  uch.CheckU_Id(Integer.valueOf(in_uid.getText()));
      // if(checkuid == true){
        //       txt_erroruid.setText("รหัสสมาชิกซ้ำ");
    
   //    }
     //  if(checkuid == false){
       //    txt_erroruid.setText("รหัสสมาชิกไม่ซ้ำ");
       
    }//GEN-LAST:event_in_uidFocusLost

    private void in_BirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_BirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_BirthdayActionPerformed

    private void in_CardIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_CardIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in_CardIdActionPerformed

    private void in_BirthdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_BirthdayFocusLost
        // TODO add your handling code here:
     if(in_Birthday.getText().isEmpty()){
         txt_errorbirthday.setText("กรุณาใส่วันเกิด ตัวอย่าง ปี-เดือน-วัน");
     }
     else{
           txt_errorbirthday.setText("");
     }
    }//GEN-LAST:event_in_BirthdayFocusLost

    private void in_TelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_TelFocusLost
        // TODO add your handling code here:
           if(in_Tel.getText().isEmpty()){
         txt_errortel.setText("กรุณาใส่เบอร์โทรศัพท์");
     }
     else{
           txt_errortel.setText("");
     }
    }//GEN-LAST:event_in_TelFocusLost

    private void in_CardIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_in_CardIdFocusLost
        // TODO add your handling code here:
          if(in_CardId.getText().isEmpty()){
         txt_errorcardid.setText("กรุณาใส่รหัสบัตรประชาชน");
     }
     else{
           txt_errorcardid.setText("");
     }
    }//GEN-LAST:event_in_CardIdFocusLost

    private void in_uidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_in_uidKeyReleased
        // TODO add your handling code here:
        User uch= new User();
        boolean checkuid =  uch.CheckU_Id(Integer.valueOf(in_uid.getText()));
       if(checkuid == true){
               txt_erroruid.setText("รหัสสมาชิกซ้ำ");
    
       }
       if(checkuid == false){
           txt_erroruid.setText("รหัสสมาชิกไม่ซ้ำ");
       }
    }//GEN-LAST:event_in_uidKeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_genneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_genneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_genneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_genneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_genneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea in_Address;
    private javax.swing.JTextField in_Birthday;
    private javax.swing.JFormattedTextField in_CardId;
    private javax.swing.JTextField in_Firstname;
    private javax.swing.JTextField in_Lastname;
    private javax.swing.JFormattedTextField in_Tel;
    private javax.swing.JTextField in_uid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_errorbirthday;
    private javax.swing.JLabel txt_errorcardid;
    private javax.swing.JLabel txt_errortel;
    private javax.swing.JLabel txt_erroruid;
    // End of variables declaration//GEN-END:variables
}
